# Generated by Django 4.1.7 on 2023-12-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250)),
                ('lname', models.CharField(max_length=250)),
                ('propic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('email', models.EmailField(max_length=250, null=True, unique=True)),
                ('psw', models.CharField(max_length=250)),
                ('addr', models.TextField(max_length=300, null=True)),
                ('utype', models.CharField(max_length=100)),
            ],
        ),
    ]
