# Generated by Django 4.1.7 on 2023-12-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regmodel',
            name='uname',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='regmodel',
            name='fname',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='regmodel',
            name='lname',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='regmodel',
            name='psw',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='regmodel',
            name='utype',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
